### ISSUE TITLE
collect_max always returns a map of size 20 regardless of the value of the last argument passed in

### ISSUE THREAD

**Issue by trevor-d** [klout/brickhouse#113]
The description for collect_max UDF expects:
_FUNC_(x, val, n) where n is the number of values to be returned.

However, it ignores the value of "n" passed in, always returning 20 elements.

**Comment by wclark** [comment]
This was fixed back in 5cb8c

trevor-d, you probably just need to update to the latest version

**Comment by kukido** [comment]
Hi Bill,
It seems that collect_max returns N number of records as long as it is less or equal to 20. Was it related to the fix you mentioned? It seems that each unit test tries to validate the result against DEFAULT_MAX_VALUE, which should not be the case, AFAIK. Will look into it more tomorrow.
Cheers,
Andrey
