### ISSUE TITLE
mvn package fails

### ISSUE THREAD

**Issue by DaimonPl** [klout/brickhouse#138]
Just tried simple `mvn package` command using Maven 3.3.3

Regardless of fact that errors are related to javadoc, such command should just work right away

`
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 42.576 s
[INFO] Finished at: 2016-09-30T07:51:49+02:00
[INFO] Final Memory: 36M/270M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.4:jar (default) on project brickhouse: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:220: error: malformed HTML
[ERROR] * return value is a map<string,double>. If three arguments
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:220: error: bad use of '>'
[ERROR] * return value is a map<string,double>. If three arguments
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:223: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:59: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:62: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:64: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:67: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:69: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:69: warning: empty <p> tag
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:70: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:72: error: malformed HTML
[ERROR] * a map of type map<string,double>, and the entire map is returned.
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:72: error: bad use of '>'
[ERROR] * a map of type map<string,double>, and the entire map is returned.
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:73: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:75: error: malformed HTML
[ERROR] * type of the map ( i.e distributed_map('mymap','map<string,bigint>'); ) and returns
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:75: error: bad use of '>'
[ERROR] * type of the map ( i.e distributed_map('mymap','map<string,bigint>'); ) and returns
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:78: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:80: error: malformed HTML
[ERROR] * maptype, (i.e distributed_map( key, 'mymap', 'map<string,bigint>') )
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/dcache/DistributedMapUDF.java:80: error: bad use of '>'
[ERROR] * maptype, (i.e distributed_map( key, 'mymap', 'map<string,bigint>') )
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomFactory.java:77: error: @param name not found
[ERROR] * @param name
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomFactory.java:77: warning: no description for @param
[ERROR] * @param name
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomFactory.java:78: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomFactory.java:80: warning: no @param for str
[ERROR] public static Filter GetBloomFilter(String str) {
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomFilter.java:67: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomFilter.java:76: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomFilter.java:76: warning: empty <p> tag
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomFilter.java:77: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomUDAF.java:33: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomUDAF.java:36: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomUDAF.java:41: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/BloomUDAF.java:43: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/DistributedBloomUDF.java:104: warning: no description for @param
[ERROR] * @param mapFilename
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/DistributedBloomUDF.java:105: warning: no description for @param
[ERROR] * @param returnEncoded
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/DistributedBloomUDF.java:106: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/DistributedBloomUDF.java:108: warning: no @throws for org.apache.hadoop.hive.ql.metadata.HiveException
[ERROR] public String evaluate(String mapFilename, Boolean returnEncoded) throws HiveException {
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/DistributedBloomUDF.java:42: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/DistributedBloomUDF.java:45: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/DistributedBloomUDF.java:47: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/bloom/DistributedBloomUDF.java:50: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/timeseries/NumericUtil.java:27: warning: no description for @param
[ERROR] * @param objInsp
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/timeseries/NumericUtil.java:28: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/timeseries/NumericUtil.java:30: warning: no @param for val
[ERROR] public static double getNumericValue(PrimitiveObjectInspector objInsp, Object val) {
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/timeseries/NumericUtil.java:51: warning: no description for @param
[ERROR] * @param val
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/timeseries/NumericUtil.java:52: warning: no description for @param
[ERROR] * @param cat
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/timeseries/NumericUtil.java:53: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/json/FromJsonUDF.java:131: warning: no description for @param
[ERROR] * @param camel
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/json/FromJsonUDF.java:132: warning: no description for @return
[ERROR] * @return
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/json/FromJsonUDF.java:38: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/json/FromJsonUDF.java:43: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/json/ToJsonUDF.java:61: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/json/ToJsonUDF.java:61: warning: empty <p> tag
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/json/ToJsonUDF.java:63: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/hll/HyperLogLogUDAF.java:39: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/date/DateRangeUDTF.java:41: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/date/DateRangeUDTF.java:44: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/date/DayDiffUDF.java:30: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/ArrayIndexUDF.java:33: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/ArrayIndexUDF.java:35: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/ArrayIndexUDF.java:35: warning: empty <p> tag
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/ArrayIndexUDF.java:36: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/CastMapUDF.java:33: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/ConditionalEmit.java:40: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/ConditionalEmit.java:43: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/ConditionalEmit.java:45: error: bad use of '>'
[ERROR] * conditional_emit( array( maxwell_score > 80 ,
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/ConditionalEmit.java:46: error: malformed HTML
[ERROR] * abs( maxwell_score - other.maxwell_score ) < 5,
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/GroupCountUDF.java:29: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/GroupCountUDF.java:29: warning: empty <p> tag
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/GroupCountUDF.java:31: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/GroupCountUDF.java:38: error: malformed HTML
[ERROR] * where group_count( ks_uid ) < 100
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/LastIndexUDF.java:31: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/LastIndexUDF.java:33: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/LastIndexUDF.java:33: warning: empty <p> tag
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/LastIndexUDF.java:34: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/MapIndexUDF.java:34: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/MapIndexUDF.java:36: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/MapIndexUDF.java:36: warning: empty <p> tag
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/MapIndexUDF.java:37: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/MultiDayCounterUDAF.java:54: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/MultiDayCounterUDAF.java:54: warning: empty <p> tag
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/collect/MurmurHash3ArrayUDF.java:25: error: unknown tag: string
[ERROR] * Evaluates the 32 bit x86 version of MurmurHash3 of array<string>.
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/sketch/CombineSketchUDF.java:37: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/sketch/CombineSketchUDF.java:39: error: unknown tag: string
[ERROR] * MD5 hashes. If array<string> is passed in, it is assumed to be
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/sketch/CombineSketchUDF.java:40: error: unknown tag: bigint
[ERROR] * the original sketch_set values; if array<bigint> is used, then
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/sketch/HashMD5UDF.java:11: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/sketch/MultiDaySketcherUDAF.java:52: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/sketch/MultiDaySketcherUDAF.java:61: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/sketch/MultiDaySketcherUDAF.java:61: warning: empty <p> tag
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/udf/sketch/SetSimilarityUDF.java:11: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/hbase/CachedGetUDF.java:29: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/hbase/CachedGetUDF.java:33: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/hbase/CachedGetUDF.java:37: error: self-closing element not allowed
[ERROR] * <p/>
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/hbase/CachedGetUDF.java:40: error: malformed HTML
[ERROR] * the from_json UDF. An example would be storing a map<string,double> as
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/hbase/CachedGetUDF.java:40: error: bad use of '>'
[ERROR] * the from_json UDF. An example would be storing a map<string,double> as
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/hbase/HTableFactory.java:87: warning: no description for @param
[ERROR] * @param configIn
[ERROR] ^
[ERROR] /home/local/dm/brickhouse/src/main/java/brickhouse/analytics/uniques/SketchSet.java:71: warning: no description for @param
[ERROR] * @param hash
[ERROR] ^
[ERROR] 
[ERROR] Command line was: /usr/lib/jvm/java-8-oracle/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/local/dm/brickhouse/target/apidocs' dir.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
`

**Comment by jeromebanks** [comment]
I've been working off a branch, but I agree this is annoying.
 commit 2c91de25a09b9c5cfe78db5abfc3656430fcfb8d turns off strict javadoc checking
