### ISSUE TITLE
Collect Distinct

### ISSUE THREAD

**Issue by dlasrado** [klout/brickhouse#139]
When we have more than 1 collect (ArrayCollectUDF) in a single hive query, there are chances of getting duplicates in each array list. 
We should have a Set version of collect to eliminate duplicates during multiple collects in a single query.

**Comment by gobrewers14** [comment]
Hive has a built-in [COLLECT_SET( )](https://cwiki.apache.org/confluence/display/Hive/LanguageManual+UDF) function.  Is that what you are looking for?

**Comment by dlasrado** [comment]
Collect_set() of hive only works with primitive types. It does not work with struts/named_struts like CollectUDF.
Hence we cannot use collect_set() when dealing with complex data types or columns.

**Comment by jeromebanks** [comment]
Can you solve the problem with the 'combine_unique' UDAF??  This aggregates lists together, and returns the union with no duplicated.

**Comment by dlasrado** [comment]
No Jerome. Even Combine_unique expects primitive data type. Please see the code below from the putIntoSet method of combine_unique().

           for (Object obj : pList) {
                Object realObj = ((**PrimitiveObjectInspector**) objInsp).getPrimitiveJavaObject(obj);
                myagg.collectSet.add(realObj);
            }
We need to handle StandardStructObjectInspector.

**Comment by dlasrado** [comment]
This issue is closed after the merge of commit #140 
Able to collect unique values of named struct.
